use_frameworks!

target 'Bugsnatch_Example' do
  pod 'Bugsnatch', :path => '../'
  pod 'Bugsnatch/Email', :path => '../'
  pod 'Bugsnatch/Productive', :path => '../'

  target 'Bugsnatch_Tests' do
    inherit! :search_paths

    
  end
end
